@php $icons=['visibility','build','school','lightbulb','workspace_premium']; @endphp
<form id="ballot-form" action="{{ $isJuror?route('jury.submit'):route('public.submit') }}" method="post">@csrf
@if($errors->any())<div class="validation-summary-errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<input type="hidden" name="presentation_id" value="{{ $form['presentationId'] }}"><input type="hidden" name="client_request_id" value="{{ $form['clientRequestId'] }}">
@foreach($ballot['criteria'] as $i=>$criterion)
@php $current=collect($form['answers']??[])->firstWhere('criterion_id',$criterion->id); @endphp
<section class="card criterion-card" data-criterion="{{ $criterion->name }}"><input type="hidden" name="answers[{{ $i }}][criterion_id]" value="{{ $criterion->id }}"><div class="criterion-title"><h2>@if(!$isJuror)<span class="material-symbols-outlined criterion-icon">{{ $icons[$i%count($icons)] }}</span>@endif<span>{{ $i+1 }}. {{ $criterion->name }}</span></h2><span class="criterion-weight">{{ number_format($criterion->weight*100) }}%</span></div>
@if($criterion->description)<p class="criterion-description">{{ $criterion->description }}</p>@endif
<div class="rating-scale" role="radiogroup" aria-label="{{ $criterion->name }}">@for($score=(int)$criterion->scale_min;$score<=(int)$criterion->scale_max;$score++)<input id="criterion-{{ $i }}-score-{{ $score }}" type="radio" name="answers[{{ $i }}][value]" value="{{ $score }}" data-max="{{ $criterion->scale_max }}" @checked((float)($current['value']??0)===$score) @required($criterion->required)><label for="criterion-{{ $i }}-score-{{ $score }}">{{ $score }}</label>@endfor</div><div class="scale-labels"><span>{{ $criterion->minimum_label }}</span><span>{{ $criterion->maximum_label }}</span></div>
@if($criterion->comment_mode!=='Hidden')<div class="criterion-comment form-group"><label for="comment-{{ $i }}">Comentario {{ $criterion->comment_mode==='Required'?'(requerido)':'(opcional)' }}</label><textarea id="comment-{{ $i }}" class="form-control" name="answers[{{ $i }}][comment]" @required($criterion->comment_mode==='Required') maxlength="2000">{{ $current['comment']??'' }}</textarea></div>@endif</section>
@endforeach
<div class="ballot-submit"><button class="button button-accent button-block" type="button" data-open-review disabled><span class="material-symbols-outlined">send</span> Revisar mi voto</button></div></form>
<dialog class="vote-dialog" id="vote-review"><h2>Revisa tu voto</h2><p>Confirma las puntuaciones antes de enviarlas. El servidor verificará nuevamente el estado de la votación.</p><ul class="review-list" data-review-list></ul><div class="dialog-actions"><button class="button button-secondary" type="button" data-close-dialog>Corregir</button><button class="button button-accent" type="submit" form="ballot-form">Enviar voto</button></div></dialog>
