@extends('layouts.public') @section('title',$event->name)
@php $fingerprint=implode('|',[$state['eventStatus'],$state['roundNumber'],$state['presentationId'],$state['presentationStatus'],$state['publicVoteCount'],$state['jurorVoteCount'],$state['currentActorHasVoted']?'True':'False',$state['timerIsPaused']?'True':'False',$state['participantFingerprint']]);$timer=$state['timerRemainingSeconds']===null?'--:--':sprintf('%02d:%02d',intdiv($state['timerRemainingSeconds'],60),$state['timerRemainingSeconds']%60); @endphp
@section('content')<header class="mobile-topbar"><a class="wordmark" href="{{ route('public.lobby') }}"><span class="material-symbols-outlined">leaderboard</span><strong>InnovaMente</strong></a><span class="connection-pill">Conectado</span></header><main class="mobile-content" data-live-poll="{{ route('public.state') }}" data-results-redirect="{{ route('projection.ranking', $event->code) }}?transition=lobby" data-poll-interval="5000" data-state="{{ $fingerprint }}"><section class="event-heading"><h1>{{ $event->name }}</h1><span class="badge {{ $state['presentationStatus']==='VotingOpen'?'badge-live':'badge-warning' }}">{{ match($state['presentationStatus']){'VotingOpen'=>'Votación abierta','OnStage'=>'Presentación en curso','VotingClosed'=>'Votación cerrada',default=>'Próxima presentación'} }}</span></section>
@if(!$state['presentationId'])<section class="card identity-card"><div class="identity-avatar"><span class="material-symbols-outlined">hourglass_top</span></div><h2>La próxima presentación comenzará en breve</h2><p>El panel se actualizará automáticamente cuando el operador seleccione al siguiente equipo.</p></section>
@else<section class="card participant-card"><span class="eyebrow">Equipo activo</span><h2>{{ $state['participantName'] }}</h2><div class="project-box"><strong>Proyecto</strong><p>{{ $state['projectTitle']?:'Propuesta de innovación' }}</p></div><x-participant-details :participant="$state" /><span class="badge badge-warning" style="margin-top:.8rem">{{ $state['presentationStatus']==='OnStage'?'Presentación en curso':'Evaluación' }}</span></section>
@if($state['presentationStatus']==='OnStage')<section class="card timer-card"><span class="eyebrow">Tiempo estimado</span>@if($state['timerEndsAt'])<div class="timer" data-countdown="{{ $state['timerEndsAt'] }}">{{ $timer }}</div>@else<div class="timer" data-paused-timer>{{ $timer }}</div>@endif<p><span class="material-symbols-outlined">schedule</span> La votación se abrirá al finalizar la exposición.</p></section><div class="lobby-action"><button class="button button-block" disabled><span class="material-symbols-outlined">how_to_vote</span> Votar</button><small>Debes esperar a que finalice la presentación para emitir tu voto.</small></div>
@elseif($state['presentationStatus']==='VotingOpen'&&!$state['currentActorHasVoted'])<section class="notice-banner"><span class="material-symbols-outlined">campaign</span><div><strong>La votación está abierta</strong><br>Evalúa al equipo que acaba de presentar.</div></section><a class="button button-accent button-block" href="{{ route('public.ballot') }}"><span class="material-symbols-outlined">how_to_vote</span> Votar ahora</a>
@elseif($state['currentActorHasVoted'])<section class="card identity-card"><div class="success-icon"><span class="material-symbols-outlined">check_circle</span></div><h2>Ya registraste tu voto</h2><p>Quédate aquí; la pantalla cambiará cuando comience la siguiente presentación.</p></section>
@else<section class="card identity-card"><div class="identity-avatar"><span class="material-symbols-outlined">lock_clock</span></div><h2>La votación ha finalizado</h2><p>Espera la próxima presentación. El estado se actualizará automáticamente.</p></section>@endif @endif</main>
<nav class="mobile-nav" aria-label="Navegación del evento"><a class="is-active" href="{{ route('public.lobby') }}"><span class="material-symbols-outlined">event</span><span>Evento</span></a><a href="{{ route('public.lobby') }}"><span class="material-symbols-outlined">how_to_vote</span><span>Votar</span></a><a href="{{ route('jury.access',['eventCode'=>$event->code]) }}"><span class="material-symbols-outlined">gavel</span><span>Jurado</span></a><a href="#"><span class="material-symbols-outlined">help</span><span>Ayuda</span></a></nav>@endsection
