@extends('layouts.admin')
@section('title','Editar jurado')

@section('content')
<header class="page-heading"><div><h1>Editar Jurado</h1><p>{{ $isGlobal ? 'Actualiza la información común del jurado en todo su historial.' : 'Actualiza la información y el peso de este jurado para el evento.' }}</p></div></header>
<section class="card admin-form-card juror-editor-card"><form action="{{ route('admin.jurors.update',$juror) }}" method="post">@csrf<input type="hidden" name="global" value="{{ $isGlobal ? 1 : 0 }}">@if($errors->any())<div class="validation-summary-errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <h2>Información del jurado</h2><div class="form-grid"><div class="form-group span-2"><label for="juror-name">Nombre</label><input id="juror-name" class="form-control" name="name" value="{{ old('name',$juror->name) }}" required maxlength="180"></div><div class="form-group"><label for="juror-title">Título o rol</label><input id="juror-title" class="form-control" name="title" value="{{ old('title',$juror->title) }}" maxlength="180"></div><div class="form-group"><label for="juror-email">Correo</label><input id="juror-email" class="form-control" name="email" type="email" value="{{ old('email',$juror->email) }}" maxlength="254"></div>@if(!$isGlobal)<div class="form-group"><label for="juror-weight">Peso individual</label><input id="juror-weight" class="form-control" name="individual_weight" type="number" min=".1" max="10" step=".1" value="{{ old('individual_weight',$juror->individual_weight) }}"><small class="form-hint">Este peso sólo aplica a {{ $juror->event->name }}.</small></div>@else<div class="form-group span-2"><small class="form-hint">El peso se configura de forma independiente dentro de cada evento y no se modifica desde el historial.</small></div>@endif</div><div class="page-actions" style="margin-top:1.2rem"><a class="button button-secondary" href="{{ $event ? route('admin.jurors',$event) : route('admin.jurors.all') }}">Cancelar</a><button class="button" type="submit"><span class="material-symbols-outlined">save</span> Guardar cambios</button></div>
</form></section>
@endsection
