@extends('layouts.admin')
@section('title','Gestión de jurados')

@section('content')
<header class="page-heading"><div><h1>Gestión de Jurados</h1><p>Administra accesos, pesos de evaluación y actividad.</p></div><button class="button" type="button" onclick="document.getElementById('juror-dialog').showModal()"><span class="material-symbols-outlined">add</span> Nuevo jurado</button></header>

@if($issued = session('issuedJuror'))
<section class="card issued-access" aria-live="polite"><div><span class="eyebrow">Acceso generado · {{ $issued['eventName'] }} ({{ $issued['eventCode'] }})</span><h2>{{ $issued['name'] }}</h2><strong class="issued-access-code">{{ $issued['code'] }}</strong><p>Este código sólo se muestra ahora. También puedes compartir el enlace o el QR.</p><a class="button button-secondary" href="{{ $issued['accessUrl'] }}" target="_blank" rel="noopener"><span class="material-symbols-outlined">open_in_new</span> Abrir acceso</a>@if($issued['emailSent'] === true)<small class="issued-access-note">Correo enviado al jurado.</small>@elseif($issued['emailSent'] === false)<small class="issued-access-note">No se pudo enviar el correo; comparte el acceso desde aquí.</small>@else<small class="issued-access-note">Este jurado no tiene correo registrado.</small>@endif</div><img class="issued-access-qr" src="{{ $issued['qrDataUri'] }}" alt="QR de acceso de {{ $issued['name'] }}"></section>
@endif

<section class="metric-grid"><article class="card metric-card"><span class="metric-label">Total jurados</span><div class="metric-value">{{ $jurors->count() }}</div></article><article class="card metric-card"><span class="metric-label">Acceso validado</span><div class="metric-value">{{ $jurors->whereNotNull('last_access_at')->count() }}</div></article><article class="card metric-card"><span class="metric-label">Revocados / bloqueados</span><div class="metric-value">{{ $jurors->where('status','!=','Active')->count() }}</div></article></section>

<section class="card panel"><header class="panel-header"><h2>{{ $event->name }}</h2><span class="form-hint">Los códigos originales nunca pueden recuperarse.</span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Jurado</th><th>Correo</th><th>Estado</th><th>Peso</th><th>Última actividad</th><th>Evaluaciones</th><th>Acciones</th></tr></thead><tbody>@forelse($jurors as $juror)<tr><td><div class="table-title">{{ $juror->name }}</div><div class="table-subtitle">{{ $juror->title ?: 'Sin rol definido' }}</div></td><td>{{ $juror->email ?: 'Sin correo' }}</td><td><span class="badge {{ $juror->status==='Active'?'badge-success':'badge-warning' }}">{{ $juror->status }}</span></td><td>{{ number_format($juror->individual_weight,2) }}</td><td>{{ $juror->last_access_at?->setTimezone('America/Santo_Domingo')->format('d/m H:i')??'Sin actividad' }}</td><td>{{ $juror->completed_evaluations }}</td><td><div class="table-actions"><a class="icon-button" href="{{ route('admin.jurors.edit',$juror) }}" title="Editar jurado"><span class="material-symbols-outlined">edit</span></a><form action="{{ route('admin.jurors.regenerate',$juror) }}" method="post">@csrf<button class="icon-button" data-confirm="El código anterior dejará de funcionar. ¿Continuar?" title="Regenerar"><span class="material-symbols-outlined">key</span></button></form><form action="{{ route('admin.jurors.revoke',$juror) }}" method="post">@csrf<button class="icon-button" data-confirm="Se cerrarán las sesiones activas. ¿Revocar acceso?" title="Revocar"><span class="material-symbols-outlined">block</span></button></form></div></td></tr>@empty<tr><td colspan="7"><div class="empty-state"><span class="material-symbols-outlined">groups</span><h3>Aún no hay jurados</h3><p>Agrega el primer jurado para generar su acceso.</p></div></td></tr>@endforelse</tbody></table></div></section>

<dialog class="vote-dialog" id="juror-dialog"><form action="{{ route('admin.jurors.add') }}" method="post">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><h2>Nuevo jurado</h2><div class="form-group juror-picker" data-juror-picker><label>Nombre</label><input class="form-control" name="name" required maxlength="180" autocomplete="off" data-juror-search aria-autocomplete="list" aria-controls="juror-suggestions"><div class="juror-suggestions" id="juror-suggestions" data-juror-results role="listbox"></div><small class="form-hint">Escribe al menos dos letras para reutilizar los datos de un jurado existente.</small></div><div class="form-group"><label>Título o rol</label><input class="form-control" name="title" maxlength="180" data-juror-title></div><div class="form-group"><label>Correo opcional</label><input class="form-control" name="email" type="email" maxlength="254" data-juror-email></div><div class="form-group"><label>Peso individual</label><input class="form-control" name="individual_weight" type="number" min=".1" max="10" step=".1" value="1"></div><div class="dialog-actions"><button class="button button-secondary" type="button" onclick="this.closest('dialog').close()">Cancelar</button><button class="button" type="submit">Generar acceso</button></div></form></dialog>
@endsection
