@extends('layouts.public')
@section('title','Acceso al evento') @section('body-class','access-page')
@section('content')
@php $clean=strtoupper(str_replace(['-',' '],'',$model['eventCode']??'')); @endphp
<main class="ambient-page"><div class="public-shell"><header class="brand-lockup"><img src="{{ asset('images/logo-innovatep.png') }}" alt="INNOVATEP InnovaMente"><h1>Plataforma de Votación</h1><p>{{ $model['requiresIdentity']?'Identifícate para continuar al evento':'Ingresa el código del evento para participar' }}</p></header>
<form class="card access-card" action="{{ route('event.access') }}" method="post">@csrf
<input type="hidden" id="device-id" name="device_id" data-device-id-input value="{{ old('device_id') }}">
@if($errors->any())<div class="validation-summary-errors"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<label class="sr-only" for="event-code">Código del evento</label><input type="hidden" id="event-code" name="event_code" value="{{ old('event_code',$model['eventCode']) }}"><div class="segmented-code" data-segmented-code data-target="#event-code" aria-label="Código de evento de seis caracteres">@for($i=0;$i<6;$i++)<input type="text" inputmode="text" autocomplete="off" maxlength="1" data-code-character aria-label="Carácter {{ $i+1 }} del código" value="{{ $clean[$i]??'' }}">@if($i===2)<span class="segmented-separator" aria-hidden="true">–</span>@endif @endfor</div>
@if($model['requiresIdentity'])<div class="form-group access-identity"><label for="display-name">Tu nombre</label><input id="display-name" class="form-control" name="display_name" value="{{ old('display_name') }}" autocomplete="name" maxlength="180" placeholder="Escribe tu nombre y apellido"><small class="form-hint">Usaremos este nombre para identificar tu voto ante la organización.</small></div>@endif
@if($model['requiresAccessCredential']||$model['accessMode']==='Hybrid')<div class="form-group access-credential"><label for="access-credential">{{ $model['accessMode']==='AttendeeList'?'Identificador del asistente':'Código personal' }}</label><input id="access-credential" class="form-control" name="access_credential" value="{{ old('access_credential') }}" autocomplete="one-time-code" placeholder="Ingresa el dato entregado por la organización">@if($model['accessMode']==='Hybrid')<small class="form-hint">Opcional: también puedes entrar con este dispositivo.</small>@endif</div>@endif
<button class="button button-block" type="submit">Entrar al evento <span class="material-symbols-outlined">arrow_forward</span></button></form><div class="access-actions"><a class="jury-link" href="{{ route('jury.access',['eventCode'=>$model['eventCode']]) }}"><span class="material-symbols-outlined">gavel</span>¿Eres jurado? Accede aquí</a><a class="support-link" href="mailto:soporte@innovamente.local"><span class="material-symbols-outlined">support_agent</span>¿Necesitas ayuda? Contacta a soporte</a></div></div></main>
@endsection
