@php
    $eventId = isset($event) ? $event->id : null;
    $isEventContext = (bool)$eventId;
    $active = fn(string $name) => request()->routeIs($name) ? 'is-active' : '';
@endphp
<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#042E80"><title>@yield('title') · Admin InnovaMente</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Montserrat:wght@700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,0&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/site.css') }}">@stack('head')</head>
<body class="admin-body">
<aside class="admin-sidebar" id="admin-sidebar"><a class="admin-brand" href="{{ route('admin.index') }}"><span>Admin</span><strong>InnovaMente</strong></a>
<nav class="admin-nav" aria-label="Navegación administrativa"><a class="{{ $active('admin.index') }}" href="{{ route('admin.index') }}"><span class="material-symbols-outlined">dashboard</span><span>Dashboard</span></a>
@if(!$isEventContext)
<a href="{{ route('admin.index') }}#event-directory"><span class="material-symbols-outlined">inventory_2</span><span>Proyectos</span></a><a class="{{ $active('admin.jurors.all') }}" href="{{ route('admin.jurors.all') }}"><span class="material-symbols-outlined">groups</span><span>Jurados</span></a><a class="{{ $active('admin.results.all') }}" href="{{ route('admin.results.all') }}"><span class="material-symbols-outlined">emoji_events</span><span>Resultados</span></a>
@else
<a class="{{ $active('admin.events.edit') }}" href="{{ route('admin.events.edit',$eventId) }}"><span class="material-symbols-outlined">settings</span><span>Configuración del evento</span></a><a class="{{ $active('admin.participants') }}" href="{{ route('admin.participants',$eventId) }}"><span class="material-symbols-outlined">inventory_2</span><span>Participantes</span></a><a class="{{ $active('admin.jurors') }}" href="{{ route('admin.jurors',$eventId) }}"><span class="material-symbols-outlined">groups</span><span>Jurados</span></a><a class="{{ $active('admin.voters') }}" href="{{ route('admin.voters',$eventId) }}"><span class="material-symbols-outlined">how_to_reg</span><span>Votantes</span></a><a class="{{ $active('admin.voting') }}" href="{{ route('admin.voting',$eventId) }}"><span class="material-symbols-outlined">tune</span><span>Evaluación</span></a><a class="{{ $active('admin.live') }}" href="{{ route('admin.live',$eventId) }}"><span class="material-symbols-outlined">live_tv</span><span>Control en vivo</span></a><a class="{{ $active('admin.event.results') }}" href="{{ route('admin.event.results',$eventId) }}"><span class="material-symbols-outlined">emoji_events</span><span>Resultados</span></a><a class="{{ $active('admin.reports') }}" href="{{ route('admin.reports',$eventId) }}"><span class="material-symbols-outlined">summarize</span><span>Reportes</span></a>
@endif</nav>
@if(auth()->user()->isAdministrator())<a class="admin-settings {{ $active('admin.settings') }}" href="{{ route('admin.settings') }}"><span class="material-symbols-outlined">settings</span><span>Configuración</span></a>@endif
<form class="admin-logout" action="{{ route('admin.logout') }}" method="post">@csrf<button type="submit"><span class="material-symbols-outlined">logout</span> Cerrar sesión</button></form></aside>
<div class="admin-shell {{ $isEventContext?'is-event-context':'' }}"><header class="admin-topbar" aria-label="Contexto administrativo"><button class="icon-button menu-toggle" type="button" data-menu-toggle aria-label="Abrir menú"><span class="material-symbols-outlined">menu</span></button><a class="topbar-logo" href="{{ route('admin.index') }}"><span class="material-symbols-outlined">leaderboard</span><strong>{{ $isEventContext?trim($__env->yieldContent('title')):'InnovaMente' }}</strong></a><div class="admin-user"><a href="{{ route('admin.mfa') }}" title="Seguridad de la cuenta">{{ auth()->user()->email }}</a><span class="avatar"><span class="material-symbols-outlined">person</span></span></div></header>
@if(session('success'))<div class="toast toast-success" role="status"><span class="material-symbols-outlined">check_circle</span>{{ session('success') }}</div>@endif
@if(session('error'))<div class="toast toast-error" role="alert"><span class="material-symbols-outlined">error</span>{{ session('error') }}</div>@endif
<main class="admin-content @yield('admin-content-class')">@if($isEventContext)<div class="event-context-banner"><div><span class="material-symbols-outlined">event</span><span>Estás trabajando dentro de un evento</span></div><a href="{{ route('admin.events.edit',$eventId) }}">Volver a Editar evento</a></div>@endif @yield('content')</main></div><script src="{{ asset('js/site.js') }}"></script>@stack('scripts')</body></html>
